from __future__ import annotations

from typing import Protocol, Optional, Any

class SourceEpisode(Protocol):
    """Contrat minimal : live et replay doivent se comporter pareil côté TUI."""

    def etat_courant(self) -> Any: ...
    def peut_avancer(self) -> bool: ...
    def avancer(self, action: Optional[Any] = None) -> None: ...
    def journal_recent(self, n: int = 8) -> list[Any]: ...

    def stop(self) -> None: ...
